pipeline{
  agent any

  tools{
    jdk "jdk11"
    maven "maven3"
  }

    stages('Git checkout'){
      stage{
        steps{

        }
      }

      stage("Unit Testing"){
        steps{checkout scmGit(branches: [[name: '*/main']], extensions: [], userRemoteConfigs: [[credentialsId: 'githublogin', url: 'https://github.com/MrMarga/app.git']])
           sh "mvn test"
        }
    } 
  }
}