pipeline{
  agent any

  tools{
    jdk "jdk11"
    maven "maven3"
  }

   stages{
        stage('Git Checkout') {
            steps {
                script {
                    git branch: 'main',
                    credentialsId: 'Credential ID',
                    url: 'https://github.com/MrMarga/app.git'
                }
            }
        }
    
       stage('Test'){
            steps {
              script{
                sh "mvn test"
            }
          }
        }

        stage('Checkstyle Analysis'){
            steps {
             script{
            sh "mvn checkstyle:checkstyle"
            }
        }
      
    }
   }
}